[WIFI-5702] Add: change_credentials script in docker image

diff --git a/chart/docker/clustersysteminfo b/chart/docker/clustersysteminfo
--- a/chart/docker/clustersysteminfo
+++ b/chart/docker/clustersysteminfo
@@ -1,56 +1,21 @@
 #!/bin/bash
 
-if [[ "$(which jq)" == "" ]]
-then
-  echo "You need the package jq installed to use this script."
-  exit 1
-fi
+# Constants
+export DEFAULT_CHECK_RETRIES=30
 
-if [[ "$(which curl)" == "" ]]
-then
-  echo "You need the package curl installed to use this script."
-  exit 1
-fi
+# Check dependencies
+[[ "$(which jq)" == "" ]] && echo "You need the package jq installed to use this script." && exit 1
+[[ "$(which curl)" == "" ]] && echo "You need the package curl installed to use this script." && exit 1
 
-if [[ "${OWSEC}" == "" ]]
-then
-  echo "You must set the variable OWSEC in order to use this script. Something like"
-  echo "OWSEC=security.isp.com:16001"
-  exit 1
-fi
+# Check if required environment variables were passed
+[[ -z ${OWSEC+x} ]] && echo "You must set the variable OWSEC in order to use this script. Something like" && echo "OWSEC=security.isp.com:16001" && exit 1
+[[ -z ${OWSEC_DEFAULT_USERNAME+x} ]] && echo "You must set the variable OWSEC_DEFAULT_USERNAME in order to use this script. Something like" && echo "OWSEC_DEFAULT_USERNAME=tip@ucentral.com" && exit 1
+[[ -z ${OWSEC_DEFAULT_PASSWORD+x} ]] && echo "You must set the variable OWSEC_DEFAULT_PASSWORD in order to use this script. Something like" && echo "OWSEC_DEFAULT_PASSWORD=openwifi" && exit 1
+[[ -z ${OWSEC_NEW_PASSWORD+x} ]] && echo "You must set the variable OWSEC_NEW_PASSWORD in order to use this script. Something like" && echo "OWSEC_NEW_PASSWORD=NewPass123%" && exit 1
 
-if [[ "${OWSEC_USERNAME}" == "" ]]
-then
-  echo "You must set the variable OWSEC_USERNAME in order to use this script. Something like"
-  echo "OWSEC_USERNAME=tip@ucentral.com"
-  exit 1
-fi
+[[ "${CHECK_RETRIES}" == "" ]] && [[ "${CHECK_RETRIES}" -eq "${CHECK_RETRIES}" ]] && echo "Environment variable CHECK_RETRIES is not set or is not number, setting it to the default value (${DEFAULT_CHECK_RETRIES})" && export CHECK_RETRIES=$DEFAULT_CHECK_RETRIES
 
-if [[ "${OWSEC_PASSWORD}" == "" ]]
-then
-  echo "You must set the variable OWSEC_PASSWORD in order to use this script. Something like"
-  echo "OWSEC_PASSWORD=openwifi"
-  exit 1
-fi
-
-if [[ "${CHECK_RETRIES}" == "" ]] && [[ "${CHECK_RETRIES}" -eq "${CHECK_RETRIES}" ]]
-then
-  echo "Environment variable CHECK_RETRIES is not set or is not number, setting it to the default value "
-  export CHECK_RETRIES=10
-fi
-
-# Adapt scripts for the security credentials
-# -> Username
-sed '/^username/s/username=.*/username="'$OWSEC_USERNAME'"/' owsec_cli -i
-sed '/^username/s/username=.*/username="'$OWSEC_USERNAME'"/' owgw_cli -i
-sed '/^username/s/username=.*/username="'$OWSEC_USERNAME'"/' owfms_cli -i
-sed '/^username/s/username=.*/username="'$OWSEC_USERNAME'"/' owprov_cli -i
-# -> Password
-sed '/^password/s/password=.*/password="'$OWSEC_PASSWORD'"/' owsec_cli -i
-sed '/^password/s/password=.*/password="'$OWSEC_PASSWORD'"/' owgw_cli  -i
-sed '/^password/s/password=.*/password="'$OWSEC_PASSWORD'"/' owfms_cli -i
-sed '/^password/s/password=.*/password="'$OWSEC_PASSWORD'"/' owprov_cli -i
-
+# Make sure owsec is resolvable
 export OWSEC_FQDN=$(echo $OWSEC | awk -F ':' '{print $1}')
 echo "Waiting for OWSEC FQDN ($OWSEC_FQDN) to be resolvable"
 exit_code=1
@@ -58,24 +23,38 @@ until [[ "$exit_code" -eq "0" ]]
 do
   getent hosts $OWSEC_FQDN
   exit_code=$?
+  sleep 1
 done
 echo
 
-echo "Waiting for OWSEC to be ready to respond to systeminfo requests"
-exit_code_sum=1
-until [[ "$exit_code_sum" -eq "0" ]]
+# Change/check password for owsec AND set owsec credentials
+export CHANGE_CHECK_RETRIES=${CHECK_RETRIES}
+until ./change_credentials || [[ "${CHANGE_CHECK_RETRIES}" -eq "0" ]]
 do
-  exit_code_sum=0
-  ./owsec_cli systeminfo
-  let "exit_code_sum+=$?"
-  if [[ ! -s result.json ]]
-  then
-    let "exit_code_sum+=1"
-  fi
-  let "exit_code_sum+=$(grep ErrorCode result.json | wc -l)"
+  echo "Change/check failed"
+  let "CHANGE_CHECK_RETRIES-=1"
+  echo "Retries left - $CHANGE_CHECK_RETRIES"
+  echo
   sleep 5
 done
-echo
+
+if [[ "${CHANGE_CHECK_RETRIES}" -eq "0" ]]
+then
+  echo "Run out of retries to change/check login credentials"
+  exit 3
+fi
+
+# Adapt scripts for the security credentials
+# -> Username
+sed '/^username/s/username=.*/username="'$OWSEC_DEFAULT_USERNAME'"/' owsec_cli -i
+sed '/^username/s/username=.*/username="'$OWSEC_DEFAULT_USERNAME'"/' owgw_cli -i
+sed '/^username/s/username=.*/username="'$OWSEC_DEFAULT_USERNAME'"/' owfms_cli -i
+sed '/^username/s/username=.*/username="'$OWSEC_DEFAULT_USERNAME'"/' owprov_cli -i
+# -> Password
+sed '/^password/s/password=.*/password="'$OWSEC_NEW_PASSWORD'"/' owsec_cli -i
+sed '/^password/s/password=.*/password="'$OWSEC_NEW_PASSWORD'"/' owgw_cli  -i
+sed '/^password/s/password=.*/password="'$OWSEC_NEW_PASSWORD'"/' owfms_cli -i
+sed '/^password/s/password=.*/password="'$OWSEC_NEW_PASSWORD'"/' owprov_cli -i
 
 echo "Running systeminfo checks for all components until all of them are available OR check tries are exausted ($CHECK_RETRIES)"
 exit_code_sum=1
