Add support for insta only certs
Signed-off-by: Carsten Schafer <Carsten.Schafer@kinarasystems.com>

diff --git a/docker-compose/dco b/docker-compose/dco
--- a/docker-compose/dco
+++ b/docker-compose/dco
@@ -5,6 +5,14 @@
 # It captures $1 == launch or l and runs: ... up -d,
 # but passes everything else straight to the docker-compose command.
 cmd="docker-compose"
+if command -v docker-compose > /dev/null 2>&1 ; then
+    cmd="docker-compose"
+elif command -v docker > /dev/null 2>&1 ; then
+    cmd="docker compose"
+else
+    echo "Could not find docker-compose or docker commands."
+    exit 1
+fi
 deploy_type=$(grep "^DEPLOY_TYPE=" .env | awk -F= '{ print $2 }')
 [ -z "$deploy_type" ] && deploy_type="default"
 if [[ "$deploy_type" == "letsencrypt" ]] ; then
@@ -25,6 +33,11 @@ if [[ "$1" == "clean" ]] ; then
     rm -rf *_data
 elif [[ "$1" == "launch" || "$1" == "l" ]] ; then
     set -x
+    $cmd up -d
+elif [[ "$1" == "relaunch" || "$1" == "rel" ]] ; then
+    set -x
+    $cmd down
+    sleep 5
     $cmd up -d
 else
     set -x
